#Filename: remove_scores.mcfunction
#Generated with Anvil@StarkTMA 0.5.4
#25-10-2023 01:06:44 +0100
#

scoreboard  objectives remove sugar_rush
scoreboard  objectives remove negative_one
scoreboard  objectives remove attackers_alive
scoreboard  objectives remove att_spawned
scoreboard  objectives remove attackers_killed
scoreboard  objectives remove dying_timer
scoreboard  objectives remove even
scoreboard  objectives remove game_level
scoreboard  objectives remove game_state
scoreboard  objectives remove side_level
scoreboard  objectives remove side_state
scoreboard  objectives remove player_level
scoreboard  objectives remove player_state
scoreboard  objectives remove player_id
scoreboard  objectives remove active_players
scoreboard  objectives remove players_odd
scoreboard  objectives remove hundred
scoreboard  objectives remove zero
scoreboard  objectives remove level_timer
scoreboard  objectives remove sequence_timer
scoreboard  objectives remove total_seq_timer
scoreboard  objectives remove wave_timer
scoreboard  objectives remove surge_timer
scoreboard  objectives remove random_seed
scoreboard  objectives remove random_min
scoreboard  objectives remove random_max
scoreboard  objectives remove random_number
scoreboard  objectives remove sequence_count
scoreboard  objectives remove level_id
scoreboard  objectives remove chapter_id
scoreboard  objectives remove level_index
scoreboard  objectives remove preparation_time
scoreboard  objectives remove total_level_time
scoreboard  objectives remove total_seq_time
scoreboard  objectives remove single_seq_time
scoreboard  objectives remove sequences
scoreboard  objectives remove wave_seq_time
scoreboard  objectives remove surge_seq_time
scoreboard  objectives remove wave_time
scoreboard  objectives remove wave_lead
scoreboard  objectives remove surge_lead
scoreboard  objectives remove wave_attackers
scoreboard  objectives remove surge_attackers
scoreboard  objectives remove wave_s_intvl
scoreboard  objectives remove surge_s_intvl
scoreboard  objectives remove spawn_intvl
scoreboard  objectives remove prep_zombies
scoreboard  objectives remove is_card_picker
scoreboard  objectives remove tower_cost
scoreboard  objectives remove progress_bar
scoreboard  objectives remove prog_bar_time
scoreboard  objectives remove display
scoreboard  objectives remove panel_type
scoreboard  objectives remove high_score
scoreboard  objectives remove intro_style
scoreboard  objectives remove starktma0
scoreboard  objectives remove starktma1
scoreboard  objectives remove starktma2
scoreboard  objectives remove starktma3
scoreboard  objectives remove starktma4
scoreboard  objectives remove starktma5
scoreboard  objectives remove starktma6
scoreboard  objectives remove starktma7
scoreboard  objectives remove starktma8
scoreboard  objectives remove starktma9
scoreboard  objectives remove player_is_moving