#Filename: setup_scores.mcfunction
#Generated with Anvil@StarkTMA 0.5.4
#25-10-2023 01:06:44 +0100
#

scoreboard  objectives add sugar_rush dummy Sugar_Rush
scoreboard  players set sugar_rush sugar_rush 0
scoreboard  objectives add negative_one dummy Negative_One
scoreboard  players set sugar_rush negative_one -1
scoreboard  objectives add attackers_alive dummy Attackers_Alive
scoreboard  players set sugar_rush attackers_alive 0
scoreboard  objectives add att_spawned dummy Att_Spawned
scoreboard  players set sugar_rush att_spawned 0
scoreboard  objectives add attackers_killed dummy Attackers_Killed
scoreboard  players set sugar_rush attackers_killed 0
scoreboard  objectives add dying_timer dummy Dying_Timer
scoreboard  players set sugar_rush dying_timer 0
scoreboard  objectives add even dummy Even
scoreboard  players set sugar_rush even 2
scoreboard  objectives add game_level dummy Game_Level
scoreboard  players set sugar_rush game_level 0
scoreboard  objectives add game_state dummy Game_State
scoreboard  players set sugar_rush game_state 0
scoreboard  objectives add side_level dummy Side_Level
scoreboard  players set sugar_rush side_level 0
scoreboard  objectives add side_state dummy Side_State
scoreboard  players set sugar_rush side_state 0
scoreboard  objectives add player_level dummy Player_Level
scoreboard  players set sugar_rush player_level 0
scoreboard  objectives add player_state dummy Player_State
scoreboard  players set sugar_rush player_state 0
scoreboard  objectives add player_id dummy Player_Id
scoreboard  players set sugar_rush player_id 0
scoreboard  objectives add active_players dummy Active_Players
scoreboard  players set sugar_rush active_players 0
scoreboard  objectives add players_odd dummy Players_Odd
scoreboard  players set sugar_rush players_odd 0
scoreboard  objectives add hundred dummy Hundred
scoreboard  players set sugar_rush hundred 100
scoreboard  objectives add zero dummy Zero
scoreboard  players set sugar_rush zero 0
scoreboard  objectives add level_timer dummy Level_Timer
scoreboard  players set sugar_rush level_timer 0
scoreboard  objectives add sequence_timer dummy Sequence_Timer
scoreboard  players set sugar_rush sequence_timer 0
scoreboard  objectives add total_seq_timer dummy Total_Seq_Timer
scoreboard  players set sugar_rush total_seq_timer 0
scoreboard  objectives add wave_timer dummy Wave_Timer
scoreboard  players set sugar_rush wave_timer 0
scoreboard  objectives add surge_timer dummy Surge_Timer
scoreboard  players set sugar_rush surge_timer 0
scoreboard  objectives add random_seed dummy Random_Seed
scoreboard  players set sugar_rush random_seed 0
scoreboard  objectives add random_min dummy Random_Min
scoreboard  players set sugar_rush random_min 0
scoreboard  objectives add random_max dummy Random_Max
scoreboard  players set sugar_rush random_max 0
scoreboard  objectives add random_number dummy Random_Number
scoreboard  players set sugar_rush random_number 0
scoreboard  objectives add sequence_count dummy Sequence_Count
scoreboard  players set sugar_rush sequence_count 0
scoreboard  objectives add level_id dummy Level_Id
scoreboard  players set sugar_rush level_id 0
scoreboard  objectives add chapter_id dummy Chapter_Id
scoreboard  players set sugar_rush chapter_id 0
scoreboard  objectives add level_index dummy Level_Index
scoreboard  players set sugar_rush level_index 0
scoreboard  objectives add preparation_time dummy Preparation_Time
scoreboard  players set sugar_rush preparation_time 0
scoreboard  objectives add total_level_time dummy Total_Level_Time
scoreboard  players set sugar_rush total_level_time 0
scoreboard  objectives add total_seq_time dummy Total_Seq_Time
scoreboard  players set sugar_rush total_seq_time 0
scoreboard  objectives add single_seq_time dummy Single_Seq_Time
scoreboard  players set sugar_rush single_seq_time 0
scoreboard  objectives add sequences dummy Sequences
scoreboard  players set sugar_rush sequences 0
scoreboard  objectives add wave_seq_time dummy Wave_Seq_Time
scoreboard  players set sugar_rush wave_seq_time 0
scoreboard  objectives add surge_seq_time dummy Surge_Seq_Time
scoreboard  players set sugar_rush surge_seq_time 0
scoreboard  objectives add wave_time dummy Wave_Time
scoreboard  players set sugar_rush wave_time 0
scoreboard  objectives add wave_lead dummy Wave_Lead
scoreboard  players set sugar_rush wave_lead 0
scoreboard  objectives add surge_lead dummy Surge_Lead
scoreboard  players set sugar_rush surge_lead 0
scoreboard  objectives add wave_attackers dummy Wave_Attackers
scoreboard  players set sugar_rush wave_attackers 0
scoreboard  objectives add surge_attackers dummy Surge_Attackers
scoreboard  players set sugar_rush surge_attackers 0
scoreboard  objectives add wave_s_intvl dummy Wave_S_Intvl
scoreboard  players set sugar_rush wave_s_intvl 0
scoreboard  objectives add surge_s_intvl dummy Surge_S_Intvl
scoreboard  players set sugar_rush surge_s_intvl 0
scoreboard  objectives add spawn_intvl dummy Spawn_Intvl
scoreboard  players set sugar_rush spawn_intvl 0
scoreboard  objectives add prep_zombies dummy Prep_Zombies
scoreboard  players set sugar_rush prep_zombies 0
scoreboard  objectives add is_card_picker dummy Is_Card_Picker
scoreboard  players set sugar_rush is_card_picker 0
scoreboard  objectives add tower_cost dummy Tower_Cost
scoreboard  players set sugar_rush tower_cost 0
scoreboard  objectives add progress_bar dummy Progress_Bar
scoreboard  players set sugar_rush progress_bar 0
scoreboard  objectives add prog_bar_time dummy Prog_Bar_Time
scoreboard  players set sugar_rush prog_bar_time 0
scoreboard  objectives add display dummy Display
scoreboard  players set sugar_rush display 999999999
scoreboard  objectives add panel_type dummy Panel_Type
scoreboard  players set sugar_rush panel_type 0
scoreboard  objectives add high_score dummy High_Score
scoreboard  players set sugar_rush high_score 0
scoreboard  objectives add intro_style dummy Intro_Style
scoreboard  players set sugar_rush intro_style 0
scoreboard  objectives add starktma0 dummy Starktma0
scoreboard  players set sugar_rush starktma0 0
scoreboard  objectives add starktma1 dummy Starktma1
scoreboard  players set sugar_rush starktma1 0
scoreboard  objectives add starktma2 dummy Starktma2
scoreboard  players set sugar_rush starktma2 0
scoreboard  objectives add starktma3 dummy Starktma3
scoreboard  players set sugar_rush starktma3 0
scoreboard  objectives add starktma4 dummy Starktma4
scoreboard  players set sugar_rush starktma4 0
scoreboard  objectives add starktma5 dummy Starktma5
scoreboard  players set sugar_rush starktma5 0
scoreboard  objectives add starktma6 dummy Starktma6
scoreboard  players set sugar_rush starktma6 0
scoreboard  objectives add starktma7 dummy Starktma7
scoreboard  players set sugar_rush starktma7 0
scoreboard  objectives add starktma8 dummy Starktma8
scoreboard  players set sugar_rush starktma8 0
scoreboard  objectives add starktma9 dummy Starktma9
scoreboard  players set sugar_rush starktma9 0
scoreboard  objectives add player_is_moving dummy Player_Is_Moving
scoreboard  players set sugar_rush player_is_moving 0